### ISSUE TITLE
Cant compile on windows - HOME

### ISSUE THREAD

**Issue by r-k-o** [vlang/v#1104]
**V version:** 
all
**OS:** 
Win 10 / 64

F:\V>set HOME
HOMEDRIVE=C:
HOMEPATH=\Users\Dr. Frank GAIN

**What did you do?**

F:\V>curl -O https://raw.githubusercontent.com/vlang/vc/master/v.c
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  334k  100  334k    0     0   334k      0  0:00:01 --:--:--  0:00:01  793k

F:\V>gcc -std=gnu11 -w -o v.exe v.c -lm

F:\V>v -o b compiler
Looks like you are running V for the first time.
V repo not found. Go to https://vlang.io to download V.zip
or install V from source.

get home dir in the compiler can't take spaces in HOMEPATH

**Comment by r-k-o** [comment]
please fix the spaces issue, so i can use the compiler. i tried after the last fixes and it doesn't work.

**Comment by medvednikov** [comment]
Should work now, can you try please?

**Comment by lcddh** [comment]
![image](https://user-images.githubusercontent.com/5841609/61253446-aa421780-a793-11e9-81b1-ecace9948366.png)

**Comment by medvednikov** [comment]
@lcddh fixed.

**Comment by nachoverdon** [comment]
@medvednikov I still have the same issue, so it's not fixed on my end. I'm on the latest commit https://github.com/vlang/v/commit/830f63e86a659bf7bb435ed2ae2a0ce34258145b

**Comment by medvednikov** [comment]
@nachoverdon please print your output.

**Comment by nachoverdon** [comment]
![imagen](https://user-images.githubusercontent.com/6435353/61290031-27d54a00-a7cb-11e9-8041-083e38fcd53d.png)

**Comment by ntrel** [comment]
@r-k-o I have a space in my HOMEPATH and v 0.1.13 works for me. I haven't tried latest release yet.

**Comment by medvednikov** [comment]
Yes, space is no longer a problem.

**Comment by medvednikov** [comment]
I think it's `os.dir_exists()` on Windows.

**Comment by joe-conigliaro** [comment]
@r-k-o Can you please try now?
