### ISSUE TITLE
Cannot use submodules defined inside src folder

### ISSUE THREAD

**Issue by hungrybluedev** [vlang/v#15374]
**V doctor:**
```
OS: linux, Pop!_OS 22.04 LTS
Processor: 6 cpus, 64bit, little endian, AMD Ryzen 5 4500U with Radeon Graphics
CC version: cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0

getwd: /home/astro/Projects/V/scratch/sp_user
vmodules: /home/astro/.vmodules
vroot: /home/astro/Projects/V/v-main
vexe: /home/astro/Projects/V/v-main/v
vexe mtime: 2022-08-07 19:21:32
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.0 5464de4.8c33a40

Git version: git version 2.34.1
Git vroot status: weekly.2022.31-24-g8c33a40c
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 827f7452

```

**What did you do?**

First, I created a sample package for demonstration and symlinked the directory to `.vmodules`:

1. `v new sample_package`
2. `mkdir ~/.vmodules/someuser` and `ln -rs . ~/.vmodules/someuser/sample_package`
3. Added some code in the package:

```
.
├── src
│   ├── library.v
│   └── sub
│       └── another.v
├── vls.log
└── v.mod
```

**src/library.v**
```
module sample_package

pub const value = 42
```

**src/sub/another.v**
```
module sub

const sub_value = 101
```

Next, in a directory sibling to `sample_package`, I created a package user project:

1. `v new sp_user`
2. Modified the structure and source:

```
.
├── src
│   └── main.v
├── vls.log
└── v.mod
```

**src/main.v**

```v
module main

import someuser.sample_package as sp
import someuser.sample_package.sub

fn main() {
	println('hello, world!')
	println('Value of the constant is $sp.value')
	println('Value of the constant is $sub.sub_value')
}
```

I ran the project with `v run .`

**What did you expect to see?**

```
hello, world!
Value of the constant is 42
Value of the constant is 101
```

**What did you see instead?**
```
src/main.v:4:1: builder error: cannot import module "someuser.sample_package.sub" (not found)
    2 | 
    3 | import someuser.sample_package as sp
    4 | import someuser.sample_package.sub
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    5 | 
    6 | fn main() {
```

**Comment by l1mey112** [comment]
It is fixed for me when I create a v.mod inside the src/ folder and the module folder.

**Comment by hungrybluedev** [comment]
> It is fixed for me when I create a v.mod inside the src/ folder and the module folder.

That's strange, I'm still getting the same error, even after adding `v.mod` in every directory.

**Comment by Casper64** [comment]
I was struggling with this for a time, but for me the issue was resolved when no `.v` file exists at the module's root level folder

So this is my remaining package structure
```
.
├── submodule1
│   └── submodule1.v
├── submodule2
│   └── submodule2.v
├── src
│   ├── other.v
│   └── mymodule.v
├── ... git files
└── v.mod
```
Each file in `src/` contains
```
module mymodule
// ...
```
And for a file in a submodule e.g. `submodule1/submodule1.v`
```
module submodule1
// ...
```
When I put this folder in `~/.vmodules/mymodule` via a soft symlink like @hungrybluedev did in his original question. I was able to import the bare submodule from any v file

```
import mymodule.submodule1

test := submodule1.SomeStruct{}
```

**Comment by qtc-de** [comment]
As far as I can tell, the current situation is still as described by @Casper64. Despite his suggested module format is working, I think that it is not the way it's supposed to be. From my point of view, if a project contains a `src` folder I expect to find the complete source code (main module and submodules) in it. Therefore, I prefer the following module structure:

```
.
├── src
│   ├── other.v
│   └── mymodule.v
│   └── submodule1
│       └── submodule1.v
│   └── submodule2
│       └── submodule2.v
├── ... git files
└── v.mod
```

However, this is still not working in the current version of *v* :disappointed: At least, documentation should be added how to create submodules and how the expected folder structure has to look like.

**Comment by joe-conigliaro** [comment]
Indeed this issue has been known for a while, I will have a think about it.
