### ISSUE TITLE
Folder names with spaces aren't processed correctly on Windows 10 Pro

### ISSUE THREAD

**Issue by M4SSD35TRUCT10N** [vlang/v#1847]
**V version:** V 0.1.18 
**OS:** Windows 10 Pro 1809 Build 17763.678

**What did you do?**
`e:\Program Files\vlang\v>v run examples\news_fetcher.v`

**What did you expect to see?**
Some news...
 
**What did you see instead?**
```v Files\vlang\v\thirdparty\cJSON\cJSON.o not found, building it...
ls() couldnt open dir "Files\vlang\v\thirdparty\cJSON" (does not exist).
Der Befehl "gcc" ist entweder falsch geschrieben oder

konnte nicht gefunden werden.
Files\vlang\v\thirdparty\cJSON\cJSON.o not found, building it...
ls() couldnt open dir "Files\vlang\v\thirdparty\cJSON" (does not exist).
Der Befehl "gcc" ist entweder falsch geschrieben oder

konnte nicht gefunden werden.
Der Befehl "gcc" ist entweder falsch geschrieben oder

konnte nicht gefunden werden.
V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
```

v was successfully build before with MSVC.

**Comment by M4SSD35TRUCT10N** [comment]
I did some further research:
`v.exe -show_c_cmd run examples\news_fetcher.v`
shows
`==========
gcc  -std=gnu11 -w -g -Werror=implicit-function-declaration -o examples\news_fetcher "e:\Users\Enrico Lefass\Documents\tenebris\v\examples\news_fetcher.tmp.c" -I e:\Users\Enrico Lefass\Documents\tenebris\v/thirdparty/cJSON e:\Users\Enrico Lefass\Documents\tenebris\v\thirdparty\cJSON\cJSON.o -lws2_32 -I e:\Users\Enrico Lefass\Documents\tenebris\v/thirdparty/vschannel -l ws2_32 -l crypt32 -l Urlmon  -DUNICODE -D_UNICODE
Der Befehl "gcc" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose`

I'm on Windows with installed MSVC, so I assume that I can compile v's C code on windows with MSVC.

Hope it helps.

**Comment by M4SSD35TRUCT10N** [comment]
Seems that `pub fn dir_exists(path string) bool { ... }` breaks something maybe the `replace` or the `to_wide` function.

As you can see sometimes / are converted to \ and the paths are complete with `v.exe -show_c_cmd run examples\news_fetcher.v` but not without the `-show_c_cmd` option.

**Comment by vitalyster** [comment]
Right now you should use `-os msvc` switch to build with Microsoft C compiler

**Comment by M4SSD35TRUCT10N** [comment]
Again fooled by lazyness but it doesn't change the main problem (paths are still crippled). And `replace` / with \ seems not to work consequently.

```
Lefass\Documents\tenebris\v\thirdparty\cJSON\cJSON.obj not found, building it (with msvc)...
ls() couldnt open dir "Lefass\Documents\tenebris\v\thirdparty\cJSON" (does not exist).
thirdparty cmd line: ""C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.20.27508\bin\Hostx64\x64\cl.exe" /volatile:ms /Z7 -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt" -I "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.20.27508\include" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared" /c  /Fo"Lefass\Documents\tenebris\v\thirdparty\cJSON\cJSON.obj" /D_UNICODE /DUNICODE"
Microsoft (R) C/C++-Optimierungscompiler Version 19.20.27508.1 f�r x64
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

cl : Befehlszeile error D8003 : Name der Quelldatei fehlt.
Lefass\Documents\tenebris\v\thirdparty\cJSON\cJSON.obj not found, building it (with msvc)...
ls() couldnt open dir "Lefass\Documents\tenebris\v\thirdparty\cJSON" (does not exist).
thirdparty cmd line: ""C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.20.27508\bin\Hostx64\x64\cl.exe" /volatile:ms /Z7 -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt" -I "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.20.27508\include" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared" /c  /Fo"Lefass\Documents\tenebris\v\thirdparty\cJSON\cJSON.obj" /D_UNICODE /DUNICODE"
Microsoft (R) C/C++-Optimierungscompiler Version 19.20.27508.1 f�r x64
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

cl : Befehlszeile error D8003 : Name der Quelldatei fehlt.

========== cl cmd line:
""C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.20.27508\bin\Hostx64\x64\cl.exe" -w /we4013 /volatile:ms /D_UNICODE /DUNICODE /Fo"e:\Users\Enrico Lefass\Documents\tenebris\v\examples\news_fetcher.tmp.c.obj" /Z7 /MDd "e:\Users\Enrico Lefass\Documents\tenebris\v\examples\news_fetcher.tmp.c"  -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt"   -I "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.20.27508\include"   -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um"   -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared"   -I "e:\Users\Enrico"   -I "e:\Users\Enrico"  Lefass\Documents\tenebris\v/thirdparty/cJSON e:\Users\Enrico Lefass\Documents\tenebris\v\thirdparty\cJSON\cJSON.obj Lefass\Documents\tenebris\v/thirdparty/vschannel kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib vcruntime.lib ws2_32.lib ws2_32.lib crypt32.lib Urlmon.lib /link /NOLOGO /OUT:"e:\Users\Enrico Lefass\Documents\tenebris\v\examples\news_fetcher.exe" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\ucrt\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\um\x64" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.20.27508\lib\x64" /INCREMENTAL:NO /DEBUG:FULL"
==========

V error: Microsoft (R) C/C++-Optimierungscompiler Version 19.20.27508.1 f�r x64
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

cl : Befehlszeile warning D9024 : Unbekannter Typ der Quelldatei "Lefass\Documents\tenebris\v/thirdparty/cJSON", Objektdatei wird angenommen.
cl : Befehlszeile warning D9024 : Unbekannter Typ der Quelldatei "e:\Users\Enrico", Objektdatei wird angenommen.
cl : Befehlszeile warning D9024 : Unbekannter Typ der Quelldatei "Lefass\Documents\tenebris\v/thirdparty/vschannel", Objektdatei wird angenommen.
news_fetcher.tmp.c
e:\Users\Enrico Lefass\Documents\tenebris\v\examples\news_fetcher.tmp.c(124): fatal error C1083: Datei (Include) kann nicht ge�ffnet werden: "cJSON.h": No such file or directory
```

**Comment by asampal** [comment]
Paths with dashes also break V. In my case I have V installed in ...\projects-opensource\v and this results in a failure.

**Comment by joe-conigliaro** [comment]
I'm looking into this

**Comment by joe-conigliaro** [comment]
fixed

**Comment by M4SSD35TRUCT10N** [comment]
Eventually nothing has changed. I pulled current master of vc (done by make.bat) and current master of v via `git pull`, then used `v -os msvc -show_c_cmd run examples\news_fetcher.v` and it shows exactly the same messages and log as before. So, no it is not fixed. It is still only using the second half of the path of `e:\Program Files\[...]` (`Files\[...]`) and by doing this it can't use `thirdparty\cJSON` and fails.

I can't open this issue but it is not fixed. Btw.: I still see some `/` instead of `\` when _*cl.exe*_ spits out some warnings (D9024). See my other comment on this from yesterday.

**Comment by joe-conigliaro** [comment]
@M4SSD35TRUCT10N oops my bad i only fixed it for dash/hyphen, not spaces. I was thinking it was just hyphen. I'm re-opening. I will add another fix soon.

**Comment by joe-conigliaro** [comment]
this is fixed in #1847

**Comment by M4SSD35TRUCT10N** [comment]
Thank you for your efforts. Will look into it when I am back home. This should be in 9hrs or so. Will immediately respond.

**Comment by joe-conigliaro** [comment]
@M4SSD35TRUCT10N This issue was auto closed with the PR, it should be fixed though. Let me know how you go.
