### ISSUE TITLE
issue with doc generation tools

### ISSUE THREAD

**Issue by despiegk** [vlang/v#7343]
## port nr

```
bash-3.2$ ./v doc -f html -inline-assets -o htmldocs/ -s  -p 9000 os
vdoc: No port number specified on "-p".
```
?

## open doc server

```
bash-3.2$ ./v doc -f html -inline-assets -o htmldocs/ -s  -open  os
Serving docs on: http://localhost:8046
```

![image](https://user-images.githubusercontent.com/6021844/102222690-09094480-3ee4-11eb-9dab-6c691117ad5d.png)

no info served

## doc info doesn't seem to be complete

![image](https://user-images.githubusercontent.com/6021844/102223108-9187e500-3ee4-11eb-977c-abbcb7726c65.png)

doc string not there

![image](https://user-images.githubusercontent.com/6021844/102223158-9fd60100-3ee4-11eb-8c97-6f5d2607e612.png)

**Comment by spytheman** [comment]
The bad request part is fixed in a4d3a05. 
The other problems are not.

**Comment by spytheman** [comment]
Please do open separate issues for different problems in the future.
That makes tracking their status and fixing them much easier.

**Comment by spytheman** [comment]
The port nr part is fixed in 560c216 .

**Comment by spytheman** [comment]
The missing doc string is not there, because of a limitation of vdoc - afaik it currently parses only `//` style comments, that are immediately before a function. We should make it parse `/* */` comments in the future too, but for the moment I think the most expedient solution will be to just edit https://github.com/vlang/pcre/blob/master/regex.v so that it has the `//` style of comments.

**Comment by spytheman** [comment]
@medvednikov what do you think?

**Comment by medvednikov** [comment]
@spytheman yes we should parse /**/

For now I've just replaced them with // in the module.

**Comment by ArtemkaKun** [comment]
Hi @despiegk 

can you confirm that the problem still exists for a fresh V (0.2.4)?

**Comment by despiegk** [comment]
suggest to close
